[project]
name = 'Decentralized-Prediction-Market-Protocol'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.oracle]
path = 'contracts/oracle.clar'
clarity_version = 2
epoch = 2.5

[contracts.prediction-market]
path = 'contracts/prediction-market.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
